# [[redirects]]
#   from = "/*"
#   to = "https://www.fernandoike.com/pt/"
#   status = 301!
#   force = false
#   query = {path = ":path"}
[context.deploy-preview.environment]
  HUGO_VERSION = "0.55.1"


[context.production.environment]
   HUGO_VERSION = "0.55.1"



[build]
command = "hugo --gc --minify && cp _redirects public/_redirects"
publish = "public"